### ISSUE TITLE
my code isnt working

### ISSUE THREAD

**Issue by redstone-scratch** [MeowerBots/MeowerBot.py#16]
code:
```py3
import MeowerBot
import os

client = MeowerBot.Client('Redstone1080', os.environ['pswd'])

def on_raw_msg(msg: dict, listener: dict):
    print(f'msg: {msg["u"]}: {msg["p"]}')

client.callback(on_raw_msg)

client.start()
```

(hosted on replit)

what i want it to do is print a line in the console when there's a new message, with the message author and content

that does not happen

<small>what do you mean, i used code from the example</small>

**Comment by showierdata9978** [comment]
whats the error displayed in the console?

**Comment by redstone-scratch** [comment]
> whats the error displayed in the console?

there is none

**Comment by showierdata9978** [comment]
turn debug mode on

also, upgrade your bot to the new version of meowerbot

**Comment by showierdata9978** [comment]
@redstone-scratch

**Comment by showierdata9978** [comment]
Stale
