### ISSUE TITLE
Logging in takes too long

### ISSUE THREAD

**Issue by Bloctans** [MeowerBots/MeowerBot.py#18]
**Describe the bug**
when attempting to log into my bot, it takes a while.
Also it crashes after a bit

**To Reproduce**
I literally dont know

**Screenshots**
![image](https://user-images.githubusercontent.com/93960460/204706633-036331fd-9e9a-41c1-8132-1413e0b1b44e.png)
This is the behavior

**Comment by showierdata9978** [comment]
> **Describe the bug**
> when attempting to log into my bot, it takes a while.
> Also it crashes after a bit
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> I literally dont know
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/93960460/204706633-036331fd-9e9a-41c1-8132-1413e0b1b44e.png)
> This is the behavior

for crashing: i made the ping way to long
it always took a while 😅, its bc of cl3 src spaghetti code, i could make a cl3 equivalent that is faster (?)

**Comment by showierdata9978** [comment]
try cloning mb.py and adding time.sleep between ip, type, and trust

**Comment by showierdata9978** [comment]
cant repro with tests

**Comment by Bloctans** [comment]
try repro with thus code:
import json
from MeowerBot import Bot
import random

msgs = [
  "msg1",
  "msg2"
]

import os

joinmsg = True

os.system("pip install meowerbot --upgrade")

from MeowerBot import Bot

c = Bot(debug=True,prefix="u!")

@c.command()
def ping(ctx, *args):
  ctx.send_msg("pong")

def login(*_, **__):
  print("login CB")
  c.send_msg(msgs[random.randint(0,len(msgs)-1)])

c.callback(login, cbid="login")

c.run(user,pass)

**Comment by showierdata9978** [comment]
please put that in a code block


    ```
    yourcode`
    ```

**Comment by showierdata9978** [comment]
```py
import json
from MeowerBot import Bot
import random

msgs = [
"msg1",
"msg2"
]

import os

joinmsg = True

os.system("pip install meowerbot --upgrade")

from MeowerBot import Bot

c = Bot(debug=True,prefix="u!")

@c.command()
def ping(ctx, *args):
   ctx.send_msg("pong")

def login(*_, **__):
   print("login CB")
   c.send_msg(msgs[random.randint(0,len(msgs)-1)])

c.callback(login, cbid="login")

c.run(user,pass)
```

**Comment by showierdata9978** [comment]
still cant repro

**Comment by Bloctans** [comment]
huh?

**Comment by showierdata9978** [comment]
wait i rember repoin this when i first did the rewrite

i think it was because the listener did not get sent back. (for another init cmd)
